version: '2'
services:
  web:
    build: .
    image: elixir
    ports:
      - 8080
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      new:
        aliases:
          - database
          - rethinkdb
  rethinkdb:
    image: rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    networks:
      - new

networks:
  new:

