version: '2'
services:
  web:
    build: .
    ports:
      - 8000:8000
    working_dir: /app
    command: mix run --no-halt
    volumes:
      - ./:/app
    depends_on:
      - rethinkdb # wait to be starded

  rethinkdb:
    image: rethinkdb
    ports:
      - 8080:8080
      - 28015:28015
      - 29015:29015

